### PR TITLE
Feature/sushiswap

### PR DESCRIPTION
**Pull request by OlaStenberg**
The only thing that's different and needs changing now is this
image

Trident only sends amountIn and amountOut, while legacy have 0in 0out, 1in and 1out..
I guess we could figure out which one is in and out by amount or something, then go with trident schema.. Thoughts @matthewlilley?

### CODE REVIEW

**Comment by OlaStenberg** [comment]
Should probably prefix CPP pools in trident.. Or we could do it whenever we add more pool types, would need to resync either way

**Comment by matthewlilley** [comment]
> The only thing that's different and needs changing now is this image
> 
> Trident only sends amountIn and amountOut, while legacy have 0in 0out, 1in and 1out.. I guess we could figure out which one is in and out by amount or something, then go with trident schema.. Thoughts @matthewlilley?

Yeah, I think this changed because previously the UI would have to figure out which direction the tokens are going in & out, which I remember being super annoying.

**Comment by OlaStenberg** [comment]
> Yeah, I think this changed because previously the UI would have to figure out which direction the tokens are going in & out, which I remember being super annoying.

Yup, this is better.
image

 This will be display values most of the time, right? like the usage here:
image
Keep it as BigDecimal?

**Comment by matthewlilley** [comment]
> > Yeah, I think this changed because previously the UI would have to figure out which direction the tokens are going in & out, which I remember being super annoying.
> 
> Yup, this is better. image
> 
> This will be display values most of the time, right? like the usage here: image Keep it as BigDecimal? @matthewlilley

Roger

**Pull request closed without merging**
